wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684639648.367684
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 7
      - 23
      4: 3.11.3
      5: 0.15.2
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
